# Generated by Django 2.2.2 on 2019-06-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.IntegerField(unique=True)),
                ('email', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('complemento', models.CharField(blank=True, max_length=30, null=True)),
                ('cidade', models.CharField(max_length=60)),
                ('estado', models.CharField(max_length=60)),
                ('cep', models.IntegerField()),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255, unique=True)),
                ('nome_fantasia', models.CharField(max_length=255)),
                ('cnpj', models.IntegerField(unique=True)),
                ('email', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('complemento', models.CharField(blank=True, max_length=30, null=True)),
                ('cidade', models.CharField(max_length=60)),
                ('estado', models.CharField(max_length=60)),
                ('cep', models.IntegerField()),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=60)),
                ('descricao', models.CharField(max_length=1000, null=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('descricao', models.CharField(max_length=1000, null=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
